# vim: set ts=2 sts=2 sw=2 et:

test_image_versioned: &test_image_versioned triton:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA:0:8}

workspace:
  base: /triton
  path: src

pipeline:
  test-docker-image:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      docker build -t triton:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA:0:8} -f Dockerfile.dev .

  test-unit:
    image: *test_image_versioned
    commands:
      - testify tests
